ESP32 force bitbang in IRAM
Makuna/NeoPixelBus pull request #446
Opened 2021-03-07 09:10 UTC by s-hadinger

Proposed fix to #445

I'm proposing to create a single `NeoEspBitBangBase_send_pixels()` function statically compiled with `IRAM` attribute. The templated method is just a wrapper.

Confirmed to work and forcing `NeoEspBitBangBase_send_pixels()` into IRAM.

2021-03-07 09:37 UTC, Makuna commented
did you try leaving it as a member static but moved into the cpp?

2021-03-07 09:47 UTC, s-hadinger commented
Yes I tried it. Then you need to instantiate all possible templates otherwise yiu get a link error. But even doing so the method wouldn't be in IRAM. 

The only other way I found was to declare specialization of the method for each template value. But it means duplicating the code to as many variants of the template. Which is nonsense.

2021-03-08 21:06 UTC, Makuna commented
Does this work and has it been tested for Esp8266?  The reason I ask is that you added an branch (if statement) in the tightest loop for the invert functionality; on Esp8266 it was already pretty tight on the timing.

2021-03-08 21:17 UTC, s-hadinger commented
No ni haven't tried with esp8266 because I don't have devices at hand for testing. 

I will propose an alternative implementation to remove the `if` statement and reduce code. In a nutshell I will split the implementation in two variants and only one will be kept by the linker 

I will measure the code size differences.

2021-03-09 11:45 UTC, s-hadinger commented
I have pushed the new version.There is no more if, and there are two implementations for normal and inverted.

I checked the code size, the new implementation is actually 8 bytes smaller. I suspect that passing as register arguments is slightly smaller than fetching the globals.

2021-03-09 18:22 UTC, Makuna commented
Could you copy and paste the output of the compile for the lines that include the memory and code use; with your changes applied.  The ones like...
```
Sketch uses ...
Global variables use ...
```

Please use the following sketch
```
#include <NeoPixelBus.h>

NeoPixelBus<NeoGrbFeature, NeoEsp32BitBangWs2812xMethod> strip(64,4);

void setup() {
  strip.Begin();
  strip.Show();
}

void loop() {
}
```

AGAIN, I want to stress, this is STILL not a guaranteed fix; you cannot use BITBANG on Esp32 without the chance of an interruption of the send routine.  Smaller number of pixels reduces the chance of this happening and the issue you are fixing is only reducing the time that it can happen further, not actually solving the issue of malformed data stream.

2021-03-09 20:44 UTC, s-hadinger commented
Sure, I understand. The only reason I'm willing to use bit-bang is because of M5Stack Atom Lite that has a single WS2812 led. I2S/RMT sounds like an overkill. I understand there are edge-cases, but the current version is broken on ESP32 with bitbang.
The alternative would be to completely disable bit bang for Esp32 if you prefer to drop this feature.

My previous code size measures were about IRAM size for ESP8266.

Here are the numbers for ESP32:

Usage with current version:
```
RAM:   [          ]   4.1% (used 13428 bytes from 327680 bytes)
Flash: [==        ]  15.5% (used 202520 bytes from 1310720 bytes)
```

Usage with this PR: (RAM +8, Flash +28)
```
RAM:   [          ]   4.1% (used 13436 bytes from 327680 bytes)
Flash: [==        ]  15.5% (used 202548 bytes from 1310720 bytes)
```

2021-03-10 17:57 UTC, s-hadinger commented
I did some tests with a 25 leds strip, and there are occasional glitches with Bit Bang. I have changed Tasmota to default to RMT, which works flawlessly. Anyways, this PR makes is "almost" broken, while the standard (code not in IRAM) makes Big Bang unusable on ESP32.

Again, I'm not pushing absolutely for Bit Bang on ESP32, and you might just decide to drop it completely.

2021-03-10 21:58 UTC, s-hadinger commented
No. I'm using platform.io

2021-03-10 22:45 UTC, Makuna commented
This is an Arduino project; I need you to make sure it builds within the Arduino IDE.

2021-03-11 01:02 UTC, Makuna requested changes
generally looks good, please remove the commented out old code

2021-03-13 22:20 UTC, s-hadinger commented on src/internal/NeoEspBitBangMethod.cpp
> +        // T_PINSET::setPin(pinRegister);
Done

2021-03-13 22:22 UTC, s-hadinger commented
Here are the outputs from Arduino 1.8.13 IDE for ESP32 (SDK 1.0.5), on the sketch you provided:

Output before patch:

```
Sketch uses 251436 bytes (19%) of program storage space. Maximum is 1310720 bytes.
Global variables use 13756 bytes (4%) of dynamic memory, leaving 313924 bytes for local variables. Maximum is 327680 bytes.
```

Output after patch:

```
Sketch uses 251464 bytes (19%) of program storage space. Maximum is 1310720 bytes.
Global variables use 13764 bytes (4%) of dynamic memory, leaving 313916 bytes for local variables. Maximum is 327680 bytes.
```

2021-03-13 23:42 UTC, merged